name             'my_cookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures my_cookbook'
long_description 'Installs/Configures my_cookbook'
version          '0.1.0'
