name             'yum'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache 2.0'
description      'Configures various yum components on Red Hat-like systems'
long_description 'Installs/Configures my_cookbook'
version          '3.10.0'
supports 'ubuntu'
supports 'debian', '>= 0.0.0'
supports 'centos', '>= 0.0.0'
supports 'redhat', '>= 0.0.0'

#depends 'apt'
#depends 'yum'
#depends 'yum-epel'
